---

- hosts: all

  vars:
    - node_js_version: 10.13.0
 
  tasks:  
  - import_tasks: ansible-task-disable-sudo-timeout.yml
  - import_tasks: ansible-task-install-nvm-node.yml
  - import_tasks: ansible-task-enable-sudo-timeout.yml